---
new_page_extension: md
auto_deploy: false
admin_path: exampleSite/static/admin
webhook_url: https://api.stackbit.com/project/5e7fe151ebe6ab001932e275/webhook/forestry
sections:
- type: document
  path: exampleSite/config.toml
  label: Config
  templates:
  - config
- type: directory
  path: exampleSite/content
  label: Basic Page
  create: all
  match: "*.md"
  exclude: _index.md
  templates:
  - basicpage
- type: directory
  path: exampleSite/content/posts
  label: Blog post
  create: all
  match: "**/*"
  templates:
  - post
upload_dir: exampleSite/static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.47
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  instant_preview_command: "apt-get install -y rsync && mkdir -p demo/themes/hugo-coder
    && rsync -av exampleSite/ demo \t&& rsync -av --exclude='demo' --exclude='exampleSite'
    --exclude='.git' . demo/themes/hugo-coder && hugo --source demo"
